title: "Sarvesh Dalvi — Portfolio"
name: "Sarvesh Dalvi"
description: "Sports Data & Performance Analytics"
url: "https://sarveshdalvianalytics.github.io"
repository: "sarveshdalvianalytics/sarveshdalvianalytics.github.io"

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"

# Plugins needed for remote themes and caching
plugins:
  - jekyll-include-cache
  - jekyll-remote-theme

# Include custom pages directory
include:
  - _pages

markdown: kramdown
kramdown:
  input: GFM

author:
  name: "Sarvesh Dalvi"
  bio: "Sports Data & Performance Analyst (MSc, UEL). Football-first reporting, event coding, dashboards."
  location: "London, UK"
  links:
    - label: "Email"
      url: "mailto:sarveshdlvuk@gmail.com"
    - label: "LinkedIn"
      url: "https://www.linkedin.com/in/sarveshdalvi80"
    - label: "Tableau"
      url: "https://public.tableau.com/app/profile/sarvesh.dalvi"

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/

# Defaults for project pages
defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: true
      read_time: false
      share: false
      comments: false
      classes: wide
      header:
        overlay_color: "#0e1117"
        overlay_filter: "0.25"
      sidebar:
        nav: "main"
